#cloud-config
# vim: syntax=yaml

repo_update: true

packages:
  - keychain

write_files:
- path: /etc/ssh/sshd_config
  content: |
    UseDNS no
    ClientAliveInterval 120
    Subsystem       sftp    /usr/lib/openssh/sftp-server
    AcceptEnv LANG LC_*
    AllowUsers k8s
    Match User ks8
          AllowAgentForwarding yes

runcmd:
- systemctl restart sshd
- systemctl restart ssh

output:
  output: { all: "| tee -a /var/log/cloud-init-output.log" }

final_message: "The system is up, after $UPTIME seconds"
