#cloud-config
# vim: syntax=yaml

repo_update: true

packages:
- gnupg2
- python3
- python3-pip
- openssh-client

write_files:
- path: /etc/ssh/sshd_config
  content: |
    UseDNS no
    ClientAliveInterval 340
    Subsystem       sftp    /usr/lib/openssh/sftp-server
    AcceptEnv LANG LC_*
    AllowUsers k8s
    AllowAgentForwarding yes
    PermitTTY yes
    PermitTunnel yes
    AllowTcpForwarding yes
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    PubkeyAuthentication yes

runcmd:
- systemctl restart sshd
- systemctl restart ssh

output:
  output: { all: "| tee -a /var/log/cloud-init-output.log" }

final_message: "The system is up, after $UPTIME seconds"
