#cloud-config
# vim: syntax=yaml

repo_update: true
repo_upgrade: all

write_files:
- path: /etc/ssh/sshd_config
  content: |
    UseDNS no
    ClientAliveInterval 240
    Subsystem       sftp    /usr/lib/openssh/sftp-server
    AcceptEnv LANG LC_*
    AllowUsers ${user}
    UsePAM yes
    PubkeyAuthentication yes
    PasswordAuthentication no
    ChallengeResponseAuthentication no

runcmd:
- systemctl restart sshd
- systemctl restart ssh

output:
  output: { all: "| tee -a /var/log/cloud-init-output.log" }

final_message: "The system is up, after $UPTIME seconds"
