#cloud-config
# vim: syntax=yaml

repo_update: true
repo_upgrade: all

packages:
  - build-essential
  - curl
  - gnupg2
  - htop
  - git-core
  - apt-transport-https
  - ca-certificates
  - keychain
  - unattended-upgrades

runcmd:
- apt-get remove sshguard -y
- apt-get remove --auto-remove sshguard -y


output:
  output: { all: "| tee -a /var/log/cloud-init-output.log" }

final_message: "The system is up, after $UPTIME seconds"
